### ISSUE TITLE
How to provide action to the robot in the episode

### ISSUE THREAD

**Issue by AnandSingh-0619** [AnandSingh-0619/habitat-lab#2]
https://github.com/AnandSingh-0619/habitat-lab/blob/07904d9e01a3bdb207438b12fe18c945f08ad49c/examples/tutorials/task.py#L247C1-L265C22

**Comment by yusufali98** [comment]
Can you copy paste the exact output message when you run the above code ?

**Comment by AnandSingh-0619** [comment]
Traceback (most recent call last):
  File "/coc/pskynet4/asingh3064/habitat-lab/examples/tutorials/task.py", line 244, in <module>
    action = pol.forward(obs)
  File "/coc/pskynet4/asingh3064/habitat-lab/habitat-lab/habitat/core/env.py", line 309, in step
    observations = self.task.step(
  File "/coc/pskynet4/asingh3064/habitat-lab/habitat-lab/habitat/tasks/rearrange/sub_tasks/pick_task.py", line 91, in step
    obs = super().step(action=action, episode=episode)
  File "/coc/pskynet4/asingh3064/habitat-lab/habitat-lab/habitat/tasks/rearrange/rearrange_task.py", line 264, in step
    obs = super().step(action=action, episode=episode)
  File "/coc/pskynet4/asingh3064/habitat-lab/habitat-lab/habitat/core/embodied_task.py", line 341, in step
    observations = self._step_single_action(
  File "/coc/pskynet4/asingh3064/habitat-lab/habitat-lab/habitat/core/embodied_task.py", line 323, in _step_single_action
    return task_action.step(
  File "/coc/pskynet4/asingh3064/habitat-lab/habitat-lab/habitat/tasks/rearrange/actions/actions.py", line 501, in step
    lin_vel, ang_vel = kwargs[self._action_arg_prefix + "base_vel"]
KeyError: 'base_vel'

**Comment by yusufali98** [comment]
Put a breakpoint [here](https://github.com/AnandSingh-0619/habitat-lab/blob/anand_dev/habitat-lab/habitat/tasks/rearrange/actions/actions.py#L501) and see what is stored in `self._action_arg_prefix`

**Comment by yusufali98** [comment]
As discussed offline, the pre-trained policy comes with the pointnav agent action space (move_forward, turn_right, turn_left, stop) but the action space of the agent in the rearrangement task is different (arm_action, base_velocity). 
You will need to explicitly define a mapping from the pointnav policy action space to the rearranegement agent action space.
