### ISSUE TITLE
Unable to load BLIP model

### ISSUE THREAD

**Issue by AnandSingh-0619** [AnandSingh-0619/habitat-lab#3]
https://github.com/AnandSingh-0619/habitat-lab/blob/e6c90be0c5bb3b555cb71f496e62ad58aefe1629/examples/tutorials/task.py#L247

Error message
Traceback (most recent call last):
  File "/coc/pskynet4/asingh3064/habitat-lab/examples/tutorials/task.py", line 247, in <module>
    model, vis_processors, _ = load_model_and_preprocess(name="blip2_t5", model_type="pretrain_flant5xxl", is_eval=True, device=device)
  File "/nethome/asingh3064/miniconda3/envs/habitat/lib/python3.9/site-packages/lavis/models/__init__.py", line 218, in load_model_and_preprocess
    return model.to(device), vis_processors, txt_processors
  File "/nethome/asingh3064/miniconda3/envs/habitat/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1160, in to
    return self._apply(convert)
  File "/nethome/asingh3064/miniconda3/envs/habitat/lib/python3.9/site-packages/torch/nn/modules/module.py", line 810, in _apply
    module._apply(fn)
  File "/nethome/asingh3064/miniconda3/envs/habitat/lib/python3.9/site-packages/torch/nn/modules/module.py", line 810, in _apply
    module._apply(fn)
  File "/nethome/asingh3064/miniconda3/envs/habitat/lib/python3.9/site-packages/torch/nn/modules/module.py", line 810, in _apply
    module._apply(fn)
  [Previous line repeated 5 more times]
  File "/nethome/asingh3064/miniconda3/envs/habitat/lib/python3.9/site-packages/torch/nn/modules/module.py", line 833, in _apply
    param_applied = fn(param)
  File "/nethome/asingh3064/miniconda3/envs/habitat/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1158, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 80.00 MiB. GPU 0 has a total capacty of 10.75 GiB of which 62.56 MiB is free. Including non-PyTorch memory, this process has 10.69 GiB memory in use. Of the allocated memory 9.44 GiB is allocated by PyTorch, and 177.73 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
(habitat) asingh3064@cortana:/srv/kira-lab/share4/asingh3064/habitat-lab/examples/tutorials$

**Comment by yusufali98** [comment]
Out of memory issue
You need to request a larger memory GPU. Start working with the A40.
